require("Core/Allowance.js");
require("Core/Bot.js");
require("Core/Channel.js");
require("Core/Config.js");
require("Core/Databases.js");
require("www/core/Enums.js");
require("Core/Users.js");
require("Core/Instance.js");
require("Core/Keys.js");
require("Core/Log.js");
require("www/core/Mapping.js");
require("Core/String Manager.js");
